### ISSUE TITLE
ds.matrixDiag resource path issue

### ISSUE THREAD

**Issue by StuartWheater** [datashield/dsBetaTestClient#110]
The following call to ``ds.matrixDiag`` generates an error message
~~~~
matrix <- c(0, 1, 2, 3, 4, 5)

res <- ds.matrixDiag(x1=matrix, aim="clientside.vector.2.matrix", nrows.scalar=6)
~~~~
The error message is:
~~~~
sim1: Not Found (404): Could not find resource for full path: https://192.168.56.100:8443/ws/datashield/session/e2eb96b2-821a-4670-b895-3526d4259e84/symbol/diag_0/diag_1/diag_2/diag_3/diag_4/diag_5?async=true
~~~~

**Comment by StuartWheater** [comment]
x1 can be a character string, a numeric vector or a scalar, but if "newobj" is null then the core below is run:
~~~~
if(is.null(newobj))
{
    newobj <- paste0("diag_",x1)
}
~~~~
which will be interesting if a numeric vector

**Comment by davraam** [comment]
Hi Stuart,

Yes, the problem is when the argument newobj is NULL and x1 is a vector. In such case newobj <- paste0("diag_",x1) returns as many names as the elements of the vector x1 (e.g. "diag_0" "diag_1" "diag_2" "diag_3" "diag_4" "diag_5").

On the other hand, if you try the following:

matrix <- c(0, 1, 2, 3, 4, 5)
res <- ds.matrixDiag(x1=matrix, aim="clientside.vector.2.matrix", nrows.scalar=6, **newobj='diagonal'**)

you can see that the matrices are assigned without any errors.

So, I suggest this modification:
if(is.null(newobj))
{
    newobj <- paste0("diag")
}

However, with this modification, if a user doesn't specify the names of the new objects and apply the function many times for different matrices, then at each time the function will overwrite a new matrix on a previous one having the same name. Therefore, I think it is also important to add a note in the headers of the function to notify the users about this behavior and recommend the use of the argument 'newobj'.

**Comment by StuartWheater** [comment]
Changed so if 'newobj' is null it will be set to "diag"
